fixed install script
Evidlo/remarkable_entware pull request #3
Opened 2019-02-01 12:12 UTC by damienchallet

A fix to fix both issues I reported

2019-02-02 05:05 UTC, Evidlo commented
Thanks.  Why is the `cd /home/root` necessary?  What if the user copies the install script and mount file to `/tmp/` instead of `/home/root`?

2019-02-02 07:07 UTC, damienchallet commented
Indeed, but the point is that your install instructions imply that the
install files end up in /home/root

On Sat, 2 Feb 2019, 06:05 Evan Widloski <notifications@github.com wrote:

> Thanks. Why is the cd /home/root necessary? What if the user copies the
> install script and mount file to /tmp/ instead of /home/root?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Evidlo/remarkable_entware/pull/3#issuecomment-459936135>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAcVPrlTYd9wz_RzEO1y5NYKEejMWzmdks5vJRytgaJpZM4aeNDg>
> .
>

2019-02-03 04:43 UTC, Evidlo requested changes

2019-02-03 04:43 UTC, Evidlo commented on entware_install.sh
>  cp opt.mount /etc/systemd/system/
How about this instead:

``` bash
parent_dir=$(dirname $0)
cp $parent_dir/opt.mount /etc/systemd/system
```

2019-02-03 10:18 UTC, damienchallet commented
Sounds good !



On Sun, Feb 3, 2019 at 5:43 AM Evan Widloski <notifications@github.com>
wrote:

> *@Evidlo* requested changes on this pull request.
> ------------------------------
>
> In entware_install.sh
> <https://github.com/Evidlo/remarkable_entware/pull/3#discussion_r253257064>
> :
>
> > @@ -84,6 +85,7 @@ fi
>  /opt/bin/opkg upgrade
>
>  # create systemd mount unit to mount over /opt on reboot
> +cd /home/root
>  cp opt.mount /etc/systemd/system/
>
> How about this instead:
>
> parent_dir=$(dirname $0)
> cp $parent_dir/opt.mount /etc/systemd/system
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Evidlo/remarkable_entware/pull/3#pullrequestreview-199338551>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAcVPia_Kj3JTNyWTg9Aq-qg6OqA75ftks5vJmjZgaJpZM4aeNDg>
> .
>

2019-02-03 20:39 UTC, Evidlo approved these changes

2019-02-03 20:43 UTC, merged

2019-02-16 21:08 UTC, Evidlo commented
Thanks